categories: [Metabolomics]
description: '[W4M][LC-MS] XCMS R Package - Preprocessing - Framework for processing
  data for high-throughput, untargeted analyte profiling'
homepage_url: http://workflow4metabolomics.org
long_description: 'Part of the W4M project: http://workflow4metabolomics.org XCMS:
  http://www.bioconductor.org/packages/release/bioc/html/xcms.html XCMS: processing
  mass spectrometry data for metabolite profiling using nonlinear peak alignment,
  matching, and identification'
name: suite_xcms
owner: lecorguille
remote_repository_url: https://github.com/workflow4metabolomics/xcms
