categories: [Metabolomics]
description: '[W4M][LC-MS] XCMS R Package - Preprocessing - peaks calling in NetCDF/mzXML
  files'
homepage_url: http://workflow4metabolomics.org
long_description: 'Part of the W4M project: http://workflow4metabolomics.org XCMS:
  http://www.bioconductor.org/packages/release/bioc/html/xcms.html Filtration and
  Peak Identification using xcmsSet function from xcms R package to preprocess LC/MS
  data for relative quantification and statistical analysis'
name: xcms_xcmsset
owner: lecorguille
remote_repository_url: https://github.com/workflow4metabolomics/xcms
